# Generated by Django 3.1.4 on 2021-01-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0002_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentclass', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynewapp.student')),
            ],
        ),
    ]
