# Generated by Django 3.1.4 on 2021-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0003_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
